/patchouli/categories汉化
ShaBaiTianCN/Skyopolis-5 pull request #14
Opened 2022-07-29 03:50 UTC by luo-2233

Co-authored-by: Zicai <25471437+13584452567@users.noreply.github.com>
Co-authored-by: 2D6 <lir732613@qq.com>
Co-authored-by: 北巳 <1321583590@qq.com>

2022-07-29 11:26 UTC, Cactusstudent requested changes

2022-07-29 11:26 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/categories/create.json
> +	"description": "推进整合包游玩进度时需要用到一些基础的机械动力模组装置，这个部分会给予你一些这方面的帮助。$(br2)你也可以将鼠标悬停在任何该模组的物品上，然后按下$(l)$(6)[$(k:forward)]$()以在帮助部分浏览模组中的这些装置。",
```suggestion
	"description": "推进整合包游玩进度时需要用到一些基础的机械动力模组装置，这个部分会给予你一些这方面的帮助。$(br2)你也可以将鼠标悬停在任何该模组的物品上，然后按下$(l)$(6)[$(k:forward)]$()以帮助你浏览模组中机械的建造。",
```

2022-07-29 11:26 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/categories/getting_started.json
> +	"description": "整合包魔改了一些东西，阅读任务和这本书来获取更多信息。",
```suggestion
	"description": "整合包对一些东西进行了魔改，阅读任务和这本书来获取更多信息。",
```

2022-07-29 11:26 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/categories/portals.json
> +	"description": "你可以搭建许多传送门以进入不同的维度。$(br2)当然，你必须先获得对应的标志物，比如进入深暗之园维度就是如此。",
```suggestion
	"description": "你可以搭建许多传送门以进入不同的维度。$(br2)当然，你必须先获得对应的通行证，比如进入深暗之园维度需要获得相应的通行证。",
```

2022-07-30 02:58 UTC, AnzhiZhang commented on patchouli_books/skyopolis/zh_cn/categories/create.json
> +	"description": "推进整合包游玩进度时需要用到一些基础的机械动力模组装置，这个部分会给予你一些这方面的帮助。$(br2)你也可以将鼠标悬停在任何该模组的物品上，然后按下$(l)$(6)[$(k:forward)]$()以在帮助部分浏览模组中的这些装置。",
```suggestion
	"description": "推进整合包游玩进度时需要用到一些基础的机械动力模组装置，这个部分会给予你一些这方面的帮助。$(br2)你也可以将鼠标悬停在任何该模组的物品上，然后按下$(l)$(6)[$(k:forward)]$()以浏览机械动力内置指南。",
```

2022-07-30 02:59 UTC, AnzhiZhang commented on patchouli_books/skyopolis/zh_cn/categories/getting_started.json
> +	"description": "整合包魔改了一些东西，阅读任务和这本书来获取更多信息。",
```suggestion
	"description": "在这个整合包中，一些东西被魔改了，阅读任务和这本书来获取更多信息！",
```

2022-07-30 05:03 UTC, Cactusstudent approved these changes

2022-07-30 05:03 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/categories/portals.json
> +	"description": "你可以搭建许多传送门以进入不同的维度。$(br2)当然，你必须先获得对应的通行证，例如进入深园维度需要深园通行证。",
```suggestion
	"description": "你可以搭建许多传送门以进入不同的维度。$(br2)但是，你必须先获得对应的通行证，例如进入深园维度需要深园通行证。",
```

2022-07-30 06:30 UTC, merged