翻译creat
ShaBaiTianCN/Skyopolis-5 pull request #25
Opened 2022-07-31 03:51 UTC by nai200

<html>
<body>

Co-authored-by: 洛 <104070571+luo-2233@users.noreply.github.com>
--

</body>
</html>

2022-07-31 03:58 UTC, Cactusstudent approved these changes

2022-07-31 03:58 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_basics.snbt
> +			title: "抽屉 (2x1)"
```suggestion
			title: "抽屉（2x1）"
```

2022-07-31 03:58 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/the_basics.snbt
> +			title: "抽屉 (2x2)"
```suggestion
			title: "抽屉（2×2）"
```

2022-07-31 03:58 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/entries/create/waterwheel.json
> +			"text": "流动的水让水车转动产生动力。"
```suggestion
			"text": "需要流动的水让水车转动产生动力。"
```

2022-07-31 03:58 UTC, Cactusstudent commented on patchouli_books/skyopolis/zh_cn/entries/create/mill.json
> +		"text": "石磨用来粉碎和研磨物品，例：$(br)(圆石 -> 沙砾)$(br)(沙砾 -> 燧石)"
```suggestion
		"text": "石磨用来粉碎和研磨物品，例：$(br)(圆石->沙砾)$(br)(沙砾->燧石)"
```

2022-07-31 04:03 UTC, Cactusstudent approved these changes

2022-07-31 04:03 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/simple_storage.snbt
> +			description: ["基础物品运输"]
```suggestion
			description: ["基础物品传输"]
```

2022-07-31 04:09 UTC, Cactusstudent requested changes
此Request Changes只针对pneumaticcraft

2022-07-31 04:15 UTC, Cactusstudent approved these changes

2022-07-31 04:15 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/pneumaticcraft_i.snbt
> +			description: ["通过在smeltery中混合种子油和强富集水来获取"]
```suggestion
			description: ["通过在冶炼炉中混合种子油和强富集水来获取"]
```

2022-07-31 04:26 UTC, Cactusstudent commented
> 某仙人掌翻译的

OK，完了吧……

2022-07-31 04:27 UTC, Cactusstudent approved these changes

2022-07-31 04:48 UTC, Cactusstudent approved these changes

2022-07-31 04:48 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/basic_blocks.snbt
> +			description: ["在草方块上使用骨粉有时会生成高草丛，这个需要用剪刀采集"]
```suggestion
			description: ["在草方块上使用骨粉有时会生成高草丛，需要用剪刀采集"]
```

2022-07-31 04:48 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/lightning.snbt
> +			description: ["可用于创建怪物刷怪蛋，可用于更改刷怪箱的刷怪类型。"]
```suggestion
			description: ["可用于制造怪物刷怪蛋，可用于更改刷怪箱的刷怪类型。"]
```

2022-07-31 04:49 UTC, Cactusstudent commented
（看完了，希望有人再review一次）

2022-07-31 11:05 UTC, AnzhiZhang requested changes
拆了重发吧，合作也没写对

2022-08-01 14:19 UTC, AnzhiZhang approved these changes
合并加上这些

```text
Co-authored-by: Duyan <Duyan013m@gmail.com>
Co-authored-by: 北巳 <1321583590@qq.com>
Co-authored-by: Cactusstudent <97865546+Cactusstudent@users.noreply.github.com>
Co-authored-by: 海福 <18917570841@163.com>
Co-authored-by: KlparetlR <3421037143@qq.com>
Co-authored-by: 洛 <104070571+luo-2233@users.noreply.github.com>
```

2022-08-01 14:24 UTC, merged