提交
ShaBaiTianCN/Skyopolis-5 pull request #26
Opened 2022-07-31 09:36 UTC by hhhfsj

2022-07-31 11:08 UTC, AnzhiZhang requested changes
revert

2022-07-31 11:08 UTC, AnzhiZhang commented on kubejs/server_scripts/world_protection.js
> +                event.player.tell(`§c该方块不能在此维度中破坏！`)
```suggestion
                event.player.tell(`§c这个方块不能在此维度中破坏！`)
```

2022-07-31 11:08 UTC, AnzhiZhang commented on kubejs/server_scripts/world_protection.js
> +            event.player.tell(`§c这个刷怪蛋不能更改刷怪笼属性！`)
```suggestion
            event.player.tell(`§c这个刷怪蛋不能在刷怪笼中使用！`)
```

2022-07-31 11:13 UTC, AnzhiZhang requested changes
revert

2022-07-31 11:13 UTC, AnzhiZhang commented on kubejs/startup_scripts/custom_stuff.js
> +  event.create('skyopolis:eroding_water').displayName('侵蚀之水').thickTexture(0x392C4C).bucketColor(0x392C4C)
```suggestion
  event.create('skyopolis:eroding_water').displayName('侵蚀水').thickTexture(0x392C4C).bucketColor(0x392C4C)
```

2022-07-31 11:13 UTC, AnzhiZhang commented on kubejs/startup_scripts/custom_stuff.js
> +event.create('skyopolis_additions:eroding_water_catalyst').displayName('侵蚀之水催化剂')
```suggestion
event.create('skyopolis_additions:eroding_water_catalyst').displayName('侵蚀水催化剂')
```

2022-07-31 11:16 UTC, AnzhiZhang requested changes

2022-07-31 11:16 UTC, AnzhiZhang commented on kubejs/client_scripts/jei_stuff.js
> +	tooltip.add(['skyopolis_additions:eroding_water_catalyst'], '投入水中将其转化为侵蚀之水')
```suggestion
	tooltip.add(['skyopolis_additions:eroding_water_catalyst'], '投入水中将其转化为侵蚀水')
```

2022-07-31 13:25 UTC, AnzhiZhang commented on kubejs/client_scripts/jei_stuff.js
> +	tooltip.add(['undergarden:virulent_mix_bucket'], '移动滚烫的流体时，桶将会被销毁（一次性）')
```suggestion
	tooltip.add(['undergarden:virulent_mix_bucket'], '转移这种液体时，桶将会被销毁！')
```

2022-07-31 13:36 UTC, Cactusstudent reviewed
L46-L48是咋回事，剩下的应该没啥问题了

2022-07-31 13:36 UTC, Cactusstudent commented on kubejs/client_scripts/jei_stuff.js
>  	tooltip.add(['skyopolis_additions:blank_bucket'], 'Drop into any skyopolis water to create a bucket of that water!')
这三条没弄？

2022-08-01 14:36 UTC, AnzhiZhang commented on kubejs/client_scripts/jei_stuff.js
>  	tooltip.add(['skyopolis_additions:blank_bucket'], 'Drop into any skyopolis water to create a bucket of that water!')
```suggestion
	tooltip.add(['minecraft:dirt'], '使用骨粉右键护根方块以创建泥土')
	tooltip.add(['minecraft:water'], '使用水催化剂右键护根方块以创建水源方块')
	tooltip.add(['skyopolis_additions:blank_bucket'], '投入任意天之城的水以获取一桶这种水！')
```

2022-08-01 14:47 UTC, AnzhiZhang approved these changes

2022-08-01 14:47 UTC, merged